### ISSUE TITLE
Webdav

### ISSUE THREAD

**Issue by mxm199** [rigon/photo-gallery#44]
1.5.0 dev, 1.5.1
When using an application to transfer photos from an android phone, **PhotoSync - Transfer Photos**, it is impossible to connect to webdav due to the error "**Expected 207 Multi-status got 200**", although nominally webdab works, other applications connect normally (X-plore File manager for example).

**Comment by rigon** [comment]
That's great! I use photo-gallery with PhotoSync all the time, it's a great
app.

I think the issue you are getting is because you need to add the directory
"/webdav" when creating the configuration in PhotoSync.

I guess I should make it more clear from the README. Thanks!
