### ISSUE TITLE
 required in type 'AlbumType'

### ISSUE THREAD

**Issue by stnc** [rigon/photo-gallery#57]
![error](https://github.com/user-attachments/assets/cfabeda2-9528-40bd-b280-b72046578747)

_**PROBLEM:**_

src/Gallery.tsx:23:7 - error TS2741: Property 'title' is missing in type '{ name: string; photos: never[]; subalbums: never[]; pseudo: false; count: number; }' but required in type 'AlbumType'.

**_SOLUTION:_**

src/Gallery.tsx:23 I added 

const defaultData: AlbumType = {
    **title: "", // I ADDED** 
    name: "",
    photos: [],
    subalbums: [],
    pseudo: false,
    count: 0,
};

**Comment by rigon** [comment]
Fixed at commit eb7e5b5.

Thanks for reporting!
